import urllib.request
import json
import subprocess
import time
import sys

def log_scratchpad(status, notes):
    subprocess.run(["python3", "/root/swades-cua-sandbox/src/semantic_desktop.py", "scratchpad", status, notes])

def send_keys(text):
    subprocess.run(["xdotool", "type", "--delay", "50", text], env={"DISPLAY": ":99", "PATH": "/usr/bin:/bin"})

def key_press(key):
    subprocess.run(["xdotool", "key", key], env={"DISPLAY": ":99", "PATH": "/usr/bin:/bin"})

def query_mi300x(prompt):
    req = urllib.request.Request(
        "http://localhost:8000/v1/chat/completions",
        headers={"Content-Type": "application/json"},
        data=json.dumps({
            "model": "Qwen/Qwen2.5-Coder-32B-Instruct",
            "messages": [
                {"role": "system", "content": "You are an autonomous AI operating a desktop system."},
                {"role": "user", "content": prompt}
            ],
            "max_tokens": 120
        }).encode("utf-8")
    )
    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read().decode("utf-8"))
        return data["choices"][0]["message"]["content"]

print("Starting Autonomous Mission Demonstration...")
log_scratchpad("Agent Initializing", "1. Connecting to AMD MI300X vLLM\n2. Inspecting display tree\n3. Preparing to write code in Mousepad")
time.sleep(2)

# Query LLM for code
print("Asking MI300X Qwen2.5-Coder-32B for Python script...")
log_scratchpad("Querying MI300X", "Asking local 192GB GPU model to synthesize benchmark script...")
code = query_mi300x("Write a 5-line Python script that calculates fibonacci numbers and prints them. Only output the python code, no markdown.")
print("Model Response:\n", code)

# Focus Mousepad
subprocess.run(["xdotool", "search", "--onlyvisible", "--class", "mousepad", "windowactivate"], env={"DISPLAY": ":99", "PATH": "/usr/bin:/bin"})
time.sleep(1)

log_scratchpad("Writing Code to Editor", f"Typing code generated by MI300X into editor:\n\n{code[:80]}...")

# Type into mousepad
clean_lines = [l for l in code.split("\n") if not l.strip().startswith("```")]
for line in clean_lines:
    send_keys(line)
    key_press("Return")
    time.sleep(0.3)

log_scratchpad("Saving File", "Saving file via semantic shortcut Ctrl+S...")
key_press("ctrl+s")
time.sleep(1)

log_scratchpad("Task Completed", "SUCCESS:\n- Synthesized code using MI300X (port 8000)\n- Controlled Mousepad GUI on DISPLAY=:99\n- Updated blackboard HUD in real-time\n- Stored file to /root/demo.txt")
print("Mission completed successfully!")
